stages:
  - test

test_enterprise-1.10:
  stage: test
  tags:
    - docker
  image: centos:7
  variables:
    BUNDLE_VERSION: "1.10.3-68-g618f48d"
  before_script:
    - echo "Using tarantool-enterprise-bundle ${BUNDLE_VERSION}"
    - curl -O -L https://tarantool:${DOWNLOAD_TOKEN}@download.tarantool.io/enterprise/tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz
    - mkdir -p tmp
    - tar -xzf tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz -C ./tmp
    - source ./tmp/tarantool-enterprise/env.sh
    - rm -rf tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz
    - tarantool -V
    - export PATH=$PWD/tmp/tarantool-enterprise:$PATH
    - yum install -y git
    - git config --global user.email "test@tarantool.io"
    - git config --global user.name "Tar Antool"
    - yum -y install https://centos7.iuscommunity.org/ius-release.rpm
    - yum -y install python36u
    - yum -y install python36u-pip
    - pip3.6 install --upgrade pip
    - pip3.6 install -r tests/python/requirements.txt
    - export PATH=.rocks/bin:$PATH
  script:
    - ./run-unit.sh
    - python3.6 -m pytest -vvl

test_opensource-1.10:
  stage: test
  tags:
    - docker
  image: centos:7
  before_script:
    - curl -L -O http://download-ib01.fedoraproject.org/pub/epel/testing/7/x86_64/Packages/t/tarantool-1.10.3.104-1.el7.x86_64.rpm
    - yum install -y tarantool-1.10.3.104-1.el7.x86_64.rpm
    - tarantool -V
    - PATH=$PWD:$PATH
    - yum install -y git
    - git config --global user.email "test@tarantool.io"
    - git config --global user.name "Tar Antool"
    - yum -y install https://centos7.iuscommunity.org/ius-release.rpm
    - yum -y install python36u
    - yum -y install python36u-pip
    - pip3.6 install --upgrade pip
    - pip3.6 install -r tests/python/requirements.txt
    - export PATH=.rocks/bin:$PATH
  script:
    - ./run-unit.sh
    - python3.6 -m pytest -vvl

test_opensource-2.2:
  stage: test
  tags:
    - docker
  image: centos:7
  before_script:
    - source ./install_tarantool2.sh
    - tarantool -V
    - PATH=$PWD:$PATH
    - yum -y install git gcc make cmake unzip
    - git config --global user.email "test@tarantool.io"
    - git config --global user.name "Tar Antool"
    - yum -y install https://centos7.iuscommunity.org/ius-release.rpm
    - yum -y install python36u
    - yum -y install python36u-pip
    - pip3.6 install --upgrade pip
    - pip3.6 install -r tests/python/requirements.txt
  script:
    - ./run-unit.sh
    - python3.6 -m pytest -vvl

